function model_num = model_tosolve(in1)
%MODEL_TOSOLVE
%    MODEL_NUM = MODEL_TOSOLVE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Jan-2022 12:16:34

Acp = in1(:,1);
Adp = in1(:,2);
H = in1(:,3);
Lc = in1(:,4);
Ld = in1(:,5);
Y = in1(:,6);
c = in1(:,7);
hh = in1(:,8);
hl = in1(:,9);
lhc = in1(:,10);
lhd = in1(:,11);
llc = in1(:,12);
lld = in1(:,13);
pc = in1(:,14);
pcL = in1(:,15);
pd = in1(:,16);
pdL = in1(:,17);
wh = in1(:,18);
wl = in1(:,19);
xc = in1(:,20);
xd = in1(:,21);
yc = in1(:,22);
yd = in1(:,23);
t2 = 1.0./wh;
t3 = 1.0./wl;
t4 = sqrt(3.0);
model_num = [c-(H.*wl).^(8.19e+2./1.0e+3),H-(8.19e+2.^(3.0./7.0).*1.0e+3.^(4.0./7.0))./1.0e+3,t3.*wh-1.0,-H+hh+hl,Y-1.0./(1.0./yc.^(3.0./2.0)+1.0./yd.^(3.0./2.0)).^(2.0./3.0),yd-yc.*(pc./pd).^(2.0./5.0),yc-Lc.*sqrt(pc).*t4.*6.578527287375533,pcL-pc.^(3.0./2.0).*t4.*4.385684858250356,yd-Ld.*sqrt(pd).*t4.*2.356562005045705e+2,pdL-pd.^(3.0./2.0).*t4.*1.571041336697137e+2,Lc-lhc.^(7.0./1.0e+1).*llc.^(3.0./1.0e+1),Ld-lhd.^(1.4e+1./2.5e+1).*lld.^(1.1e+1./2.5e+1),lhc-llc.*(pcL.*t2.*(7.0./1.0e+1)).^(1.0e+1./3.0),llc-lhc.*(pcL.*t3.*(3.0./1.0e+1)).^(1.0e+1./7.0),lhd-lld.*(pdL.*t2.*(1.4e+1./2.5e+1)).^(2.5e+1./1.1e+1),lld-lhd.*(pdL.*t3.*(1.1e+1./2.5e+1)).^(2.5e+1./1.4e+1),Acp-6.644312560249289,Adp-2.521521345398904e+2,(pc.^(3.0./5.0)+pd.^(3.0./5.0)).^(5.0./3.0)-1.0,-hh+lhc+lhd,-hl+llc+lld,xd-Ld.*(pd.*3.0).^(3.0./2.0).*2.356562005045705e+2,xc-Lc.*(pc.*3.0).^(3.0./2.0).*6.578527287375533];
