function Obj_optims = objective_ram(in1)
%OBJECTIVE_RAM
%    OBJ_OPTIMS = OBJECTIVE_RAM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Feb-2022 15:47:45

tauul = in1(:,2);
t2 = -tauul;
t4 = 1.1e+1.^(1.1e+1./2.5e+1);
t5 = 1.4e+1.^(1.4e+1./2.5e+1);
t3 = t2+1.0;
Obj_optims = tauul.*(-3.0./7.0)-log((sqrt(3.0).*5.0.^(1.4e+1./2.5e+1).*7.0.^(1.1e+1./2.5e+1).*t3.^(3.0./7.0).*t4.*t5.*(1.0./((3.0.^(7.0./1.0e+1).*7.0.^(3.0./1.0e+1).*t4.*t5.*7.466666666666667e-3).^(2.0./5.0)+1.0).^(5.0./3.0)).^(3.0./2.0).*(1.6e+1./5.25e+2)).^t3)+3.0./7.0;
