function model_param = Ramsey_model(tauul)
%RAMSEY_MODEL
%    MODEL_PARAM = RAMSEY_MODEL(TAUUL)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    07-Feb-2022 17:50:45

t2 = -tauul;
t3 = tauul-1.0;
t4 = sqrt(3.0);
t6 = 3.0.^(7.0./1.0e+1);
t7 = 7.0.^(3.0./1.0e+1);
t8 = 7.0.^(1.1e+1./2.5e+1);
t9 = 5.0.^(1.4e+1./2.5e+1);
t10 = 1.1e+1.^(1.1e+1./2.5e+1);
t11 = 1.4e+1.^(1.4e+1./2.5e+1);
t5 = t2+1.0;
t13 = t6.*t7.*t10.*t11.*7.466666666666656e-3;
t12 = t5.^(3.0./7.0);
t14 = t13.^(2.0./5.0);
t15 = t14+1.0;
t16 = 1.0./t15.^(5.0./3.0);
t17 = t16.^(3.0./2.0);
t18 = t4.*t8.*t9.*t10.*t11.*t12.*t17.*2.644468801726204e+1;
t19 = t18.^t3;
t20 = conj(t19);
model_param = -t20.*(conj(log(t18))./t20-(t3.*t4.*t8.*t9.*t10.*t11.*t17.*1.133343772168373e+1)./(conj(t5.^(4.0./7.0)).*conj(t18.^tauul)))+3.0./7.0;
