function model_param = Ramsey_model(tauul)
%Ramsey_model
%    MODEL_PARAM = Ramsey_model(TAUUL)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    17-Feb-2022 16:52:41

t2 = -tauul;
t3 = t2+1.0;
model_param = (-3.0./7.0)./(conj(t3.^(3.0./7.0)).*conj(t3.^(4.0./7.0)))+3.0./7.0;
