function model_num = model_fun(in1)
%MODEL_FUN
%    MODEL_NUM = MODEL_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Jan-2022 13:40:57

Acp = in1(:,20);
Adp = in1(:,21);
H = in1(:,19);
Lc = in1(:,11);
Ld = in1(:,12);
Y = in1(:,10);
c = in1(:,1);
hh = in1(:,5);
hl = in1(:,4);
lhc = in1(:,15);
lhd = in1(:,17);
llc = in1(:,16);
lld = in1(:,18);
pc = in1(:,6);
pcL = in1(:,13);
pd = in1(:,7);
pdL = in1(:,14);
wh = in1(:,3);
wl = in1(:,2);
yc = in1(:,8);
yd = in1(:,9);
t2 = 1.0./wh;
t3 = 1.0./wl;
t4 = sqrt(3.0);
model_num = [c-(H.*wl).^(8.19e+2./1.0e+3),H-(8.19e+2.^(3.0./7.0).*1.0e+3.^(4.0./7.0))./1.0e+3,t3.*wh-7.0./5.0,-H+hh+hl.*(7.0./5.0),Y-(sqrt(yc)+sqrt(yd)).^2,yd-pc.^2.*1.0./pd.^2.*yc,yc-Lc.*sqrt(pc).*t4.*4.0,pcL-pc.^(3.0./2.0).*t4.*(8.0./3.0),yd-Ld.*sqrt(pd).*t4.*8.0,pdL-pd.^(3.0./2.0).*t4.*(1.6e+1./3.0),Lc-lhc.^(3.0./5.0).*llc.^(2.0./5.0),Ld-lhd.^(2.1e+1./5.0e+1).*lld.^(2.9e+1./5.0e+1),lhc-llc.*(pcL.*t2.*(3.0./5.0)).^(5.0./2.0),llc-lhc.*(pcL.*t3.*(2.0./5.0)).^(5.0./3.0),lhd-lld.*(pdL.*t2.*(2.1e+1./5.0e+1)).^(5.0e+1./2.9e+1),lld-lhd.*(pdL.*t3.*(2.9e+1./5.0e+1)).^(5.0e+1./2.1e+1),Acp-1.01e+2./2.5e+1,Adp-2.18e+2./2.5e+1,1.0./(1.0./pc+1.0./pd)-1.0,-hh+lhc+lhd,-hl+llc+lld];
